name: Update Bot version

on:
  push:
    branches: [ main ]
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        id: script
        with:
          fail-on-error: false
          script: |
            import sys
            print(sys.path)
            with open("system/version") as f:
              BOT_VERSION = f.read().replace("\n", "")

            with open("system/version", "w") as f:
              f.write(str(float(BOT_VERSION)+0.1))
              print(f"Bot updated to {BOT_VERSION}")
      - name: Print errors
        if: steps.script.outputs.error == 'true'
        run: |
          printenv "SCRIPT_STDOUT"
          printenv "SCRIPT_STDERR"
        env:
          SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
          SCRIPT_STDERR: ${{ steps.script.outputs.stderr }} 
