name: Increment version

on: push

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Increment version
        run: |
          git config --global user.email "poussigalitv@gmail.com"
          git config --global user.name "GalTechDev"
          # Read the current version from the .version file
          current_version=$(cat understar/.version)

          # Increment the version number by 0.01
          new_version=$(awk -v ver="$current_version" 'BEGIN { print ver+0.01 }')

          # Update the .version file with the new version number
          echo "$new_version" > understar/.version

          # Add the modified .version file to the staging area
          git add understar/.version

          # Commit the changes with a message
          git commit -m "Increment version to $new_version"

          # Push the changes back to the repository
          git push
